### ISSUE TITLE
Show above alert dialog

### ISSUE THREAD

**Issue by jaypratapsingh** [faruktoptas/FancyShowCaseView#183] opened 2020-05-07 04:41 UTC
Hi, I just want to show this view above alert dialog as an overlay view. How can I achieve it?

**Comment by faruktoptas** [comment] 2020-05-07 06:55
Unfortunately it not supported. Because dialogs are shown on top of other views.
Duplicate of #79

**Closed by faruktoptas** 2020-05-07 06:55 UTC

**Comment by jaypratapsingh** [comment] 2020-05-07 15:34
Okay, Can you please let me know how it is working, it is creating an overlay screen above the activity/fragment?

**Comment by faruktoptas** [comment] 2020-05-07 15:49
Yes it is a FrameLayout added as a child view into the root view of activity. Here you can see the code: https://github.com/faruktoptas/FancyShowCaseView/blob/master/fancyshowcaseview/src/main/java/me/toptas/fancyshowcase/FancyShowCaseView.kt#L135
