### ISSUE TITLE
Problem in DialogFragment and BottomSheetDialogFragment

### ISSUE THREAD

**Issue by ligong0904** [faruktoptas/FancyShowCaseView#232] opened 2022-05-01 11:40 UTC
When the View that needs to be highlighted is located in the DialogFragment or BottomSheetDialogFragment, the CustomView will be displayed in the lower layer of the DialogFragment or BottomSheetDialogFragment, which means that the CustomView is blocked. Can you support the scenario of DialogFragment and BottomSheetDialogFragment?

**Comment by faruktoptas** [comment] 2023-12-23 10:58
Duplicate of #184

**Closed by faruktoptas** 2023-12-23 10:58 UTC

**Comment by andersonguermo** [comment] 2024-01-01 21:42
[OpenID-Certification-of-Conformance[1].pdf](https://github.com/faruktoptas/FancyShowCaseView/files/13806072/OpenID-Certification-of-Conformance.1.pdf)
