### ISSUE TITLE
fitSystemWindows not work on API-19

### ISSUE THREAD

**Issue by iman2420** [faruktoptas/FancyShowCaseView#112] opened 2018-08-12 17:13 UTC
I use `fitSystemWindows `in `FancyShowCaseView `. but `fitSystemWindows `not work on `api<=19`. why?

**Comment by faruktoptas** [comment] 2018-08-12 18:51
@iman2420 can you share a screenshot and your layout xml file?

**Comment by iman2420** [comment] 2018-08-13 17:08
layout xml:
    `
<?xml version="1.0" encoding="utf-8"?>
    <RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:fitsSystemWindows="true">
    ....
    ....
`
and java code:

           `
                new FancyShowCaseView.Builder(this)
                .focusOn(allDashboards)
                .enableTouchOnFocusedView(true)
                .closeOnTouch(false)
                .fitSystemWindows(true)
                .title(titleText)
                .titleStyle(R.style.ShowCaseTitleStyleMedium, Gravity.CENTER)
                .focusShape(FocusShape.ROUNDED_RECTANGLE)
                .roundRectRadius(6)
                .build()
                .show();
`

**Comment by faruktoptas** [comment] 2018-08-14 05:37
This information is not enough to find out the problem. Can you share a screenshot, whole xml layout and your theme please?

**Comment by faruktoptas** [comment] 2018-10-25 16:31
Duplicate of https://github.com/faruktoptas/FancyShowCaseView/issues/111#issuecomment-433118841

**Closed by faruktoptas** 2018-10-25 16:31 UTC
