### ISSUE TITLE
program 

### ISSUE THREAD

**Issue by 2391645784** [faruktoptas/FancyShowCaseView#65] opened 2017-08-10 01:57 UTC
can't work well in android 7.1.1!!

**Comment by faruktoptas** [comment] 2017-08-10 06:21
@2391645784 Can you give more details? What happens on 7.1.1?

**Comment by 2391645784** [comment] 2017-08-10 06:24
When I use it on project . I make the View focus on the FloatingActionButton , it can't work .   it is grey

**Comment by faruktoptas** [comment] 2017-08-10 06:36
Can you share your layout xml and the code please?

**Comment by 2391645784** [comment] 2017-08-10 06:42
<?xml version="1.0" encoding="utf-8"?>
<android.support.v4.widget.DrawerLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:id="@+id/dl_customermainAct"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:fitsSystemWindows="true"
    tools:context="com.hengtaixiangwuliu.customeractivity.CustomerMainActivity">

    <android.support.design.widget.CoordinatorLayout
        android:layout_width="match_parent"
        android:layout_height="match_parent">

        <LinearLayout
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:orientation="vertical">

            <RelativeLayout
                android:id="@+id/rv"
                android:layout_width="match_parent"
                android:layout_height="?attr/actionBarSize"
                android:background="@color/colorAccent">

                <ImageView
                    android:id="@+id/img_opendrawer_customermainAct"
                    android:layout_width="48dp"

                    android:layout_height="match_parent"
                    android:layout_alignParentLeft="true"
                    android:background="?android:attr/actionBarItemBackground"
                    android:clickable="true"
                    android:padding="12dp"
                    android:src="@drawable/customer_menu" />

                <TextView
                    android:layout_width="wrap_content"

                    android:layout_height="wrap_content"
                    android:layout_centerInParent="true"
                    android:text="ordercenter"
                    android:textColor="#fff"
                    android:textSize="20sp" />


            </RelativeLayout>
           
            <FrameLayout
                android:id="@+id/fl_container_customermainAct"
                android:layout_width="match_parent"
                android:layout_height="0dp"
                android:layout_weight="1" />

        </LinearLayout>

        <android.support.design.widget.FloatingActionButton
            android:id="@+id/fab_customermainAct"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_gravity="bottom|end"
            android:layout_margin="16dp"
            app:rippleColor="#000000"
            app:srcCompat="@drawable/order_customermain" />

    </android.support.design.widget.CoordinatorLayout>


 
    <LinearLayout

        android:layout_width="280dp"
        android:layout_height="match_parent"
        android:layout_gravity="start"
        android:background="#f2f4f5"
        android:fitsSystemWindows="true"
        android:orientation="vertical"
        tools:layout_gravity="start">
        
        <ImageView
            android:layout_width="match_parent"
            android:layout_height="160dp"
            android:layout_marginTop="24dp"
            android:scaleType="fitCenter"
            android:src="@drawable/logo_splash" />

        <View
            android:layout_width="match_parent"
            android:layout_height="1dp"
            android:background="#e5e5e5" />
       
        <LinearLayout
            android:layout_width="match_parent"
            android:layout_height="48dp"
            android:background="?android:attr/selectableItemBackground"
            android:clickable="true"
            android:gravity="center_vertical"
            android:orientation="horizontal"
            android:paddingLeft="12dp">

            <ImageView
                android:layout_width="36dp"
                android:layout_height="36dp"
                android:padding="6dp"
                android:src="@drawable/order_center" />

            <TextView

                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:layout_marginLeft="6dp"
                android:gravity="center"
                android:text="ordercenter"
                android:textColor="#000"
                android:textSize="18sp" />
        </LinearLayout>

        <View
            android:layout_width="match_parent"
            android:layout_height="1dp"
            android:layout_marginLeft="24dp"
            android:background="#e5e5e5" />
    
        <LinearLayout
            android:layout_width="match_parent"
            android:layout_height="48dp"
            android:background="?android:attr/selectableItemBackground"
            android:clickable="true"
            android:gravity="center_vertical"
            android:orientation="horizontal"
            android:paddingLeft="12dp">

            <ImageView
                android:layout_width="36dp"
                android:layout_height="36dp"
                android:padding="6dp"
                android:src="@drawable/person_customer_center" />

            <TextView

                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:layout_marginLeft="6dp"
                android:gravity="center"
                android:text="personcenter"
                android:textColor="#000"
                android:textSize="18sp" />
        </LinearLayout>

        <View
            android:layout_width="match_parent"
            android:layout_height="1dp"
            android:layout_marginLeft="24dp"
            android:background="#e5e5e5" />

     

        <LinearLayout
            android:id="@+id/ll_exitlogin_customermainAct"
            android:layout_width="match_parent"
            android:layout_height="48dp"
            android:background="?android:attr/selectableItemBackground"
            android:clickable="true"
            android:gravity="center_vertical"
            android:orientation="horizontal"
            android:paddingLeft="12dp">

            <ImageView
                android:layout_width="36dp"
                android:layout_height="36dp"
                android:padding="6dp"
                android:src="@drawable/exit_customermain" />

            <TextView

                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:layout_marginLeft="6dp"
                android:gravity="center"
                android:text="exit"
                android:textColor="#000"
                android:textSize="18sp" />
        </LinearLayout>

        <View
            android:layout_width="match_parent"
            android:layout_height="1dp"
            android:layout_marginLeft="24dp"
            android:background="#e5e5e5" />
    </LinearLayout>


</android.support.v4.widget.DrawerLayout>

**Comment by faruktoptas** [comment] 2017-08-10 06:56
can you call the `FacyShowCaseView->show()` method in `new Handler().postDelayed()` runnable?

**Comment by 2391645784** [comment] 2017-08-10 06:58
no , i didn't do it like this

**Comment by faruktoptas** [comment] 2017-08-10 07:20
can you try it?

**Comment by 2391645784** [comment] 2017-08-10 07:21
(⊙o⊙)… well

**Comment by csIng** [comment] 2017-08-22 11:39
@2391645784 @faruktoptas 
I test it in my device(android 7.1.1) with your layout resource,there has no any problem.
code like this:
`super.onCreate(savedInstanceState);
        setContentView(R.layout.test_activity);
        View view = findViewById(R.id.fab_customermainAct);
        new FancyShowCaseView.Builder(this)
                .backgroundColor(getResources().getColor(R.color.colorAccent))
                .fitSystemWindows(true)
                .focusOn(view)
                .focusBorderColor(getResources().getColor(R.color.colorPrimaryDark))
                .focusBorderSize(getResources().getDimensionPixelSize(R.dimen.one_dp))
                .build().show();`

**Comment by csIng** [comment] 2017-08-22 11:40
@2391645784 @faruktoptas
I test it in my device(android 7.1.1) with your layout resource,there has no any problem.
code like this:

`@Override
    protected void onCreate(@Nullable Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.test_activity);
        new FancyShowCaseView.Builder(this)
                .backgroundColor(getResources().getColor(R.color.colorAccent))
                .fitSystemWindows(true)
                .focusOn(findViewById(R.id.fab_customermainAct))
                .focusBorderColor(getResources().getColor(R.color.colorPrimaryDark))
                .focusBorderSize(getResources().getDimensionPixelSize(R.dimen.one_dp))
                .build().show();
    }`

**Comment by csIng** [comment] 2017-08-22 11:41
@2391645784 @faruktoptas
I test it in my device(android 7.1.1) with your layout resource,there has no any problem.
code like this:

`

super.onCreate(savedInstanceState);
        setContentView(R.layout.test_activity);
        new FancyShowCaseView.Builder(this)
                .backgroundColor(getResources().getColor(R.color.colorAccent))
                .fitSystemWindows(true)
                .focusOn(findViewById(R.id.fab_customermainAct))
                .focusBorderColor(getResources().getColor(R.color.colorPrimaryDark))
                .focusBorderSize(getResources().getDimensionPixelSize(R.dimen.one_dp))
                .build().show();

`

**Comment by faruktoptas** [comment] 2017-08-23 11:28
@csIng @2391645784 I could not reproduce the problem too.
It works well.

**Comment by faruktoptas** [comment] 2017-10-08 11:30
Closing the issue. Please reopen with more details if reproduced.

**Closed by faruktoptas** 2017-10-08 11:30 UTC
