### ISSUE TITLE
TabLayout custom view focus

### ISSUE THREAD

**Issue by lashket** [faruktoptas/FancyShowCaseView#61] opened 2017-07-31 15:30 UTC
Hi, I have a tab alyout with custom view 
```
<ImageView
    android:id="@+id/notification_tab_view"
    android:layout_width="wrap_content"
    android:layout_height="wrap_content"
    android:src="@drawable/selector_tab_notifications"
    xmlns:android="http://schemas.android.com/apk/res/android" />
```
My drawable/selector_tab_notifications looks like:

```
<selector xmlns:android="http://schemas.android.com/apk/res/android">
    <item android:state_selected="true" android:drawable="@drawable/ic_ac_tab_notif_select"/>
    <item android:drawable="@drawable/ic_ac_tab_notif"/>
</selector>
```
I'm trying to use:
```
new FancyShowCaseView.Builder(this)
                .focusOn(toolbarTabLayout.getTabAt(1).getCustomView())
                .title("Focus text")
                .build()
                .show();
```
```
new FancyShowCaseView.Builder(this)             
            .focusOn((ImageView)toolbarTabLayout.getTabAt(1).getCustomView().findViewById(R.id.notification_tab_view))
                .title("Focus text")
                .build()
                .show();

```
and nothing works. Is there a solution to this problem?

**Comment by faruktoptas** [comment] 2017-07-31 15:37
Can you check that the views you pass to focusOn() are not null?

**Comment by lashket** [comment] 2017-07-31 15:52
Yes, I checked, in each case view is not null

**Comment by faruktoptas** [comment] 2017-07-31 21:16
What is the widht/height values for the view you want to focus?

**Comment by faruktoptas** [comment] 2017-08-01 10:17
Which version of FancyShowCaseView you are using? This problem should be fixed with version 0.1.3

**Comment by lashket** [comment] 2017-08-01 11:01
yes, i used the old version of library. After updating to 0.1.4 i see this:
[screenshot](http://imgur.com/a/YsVMy)

**Comment by faruktoptas** [comment] 2017-08-01 11:44
Does your root view has fitSystemWindows=true ?

**Comment by lashket** [comment] 2017-08-01 11:58
No, but if i'm using this, it works fine
```
        new Handler().postDelayed(() ->
                new FancyShowCaseView.Builder(MainActivity.this)
                .focusOn(toolbarTabLayout.getTabAt(0).getCustomView())
                .build()
                .show(), 5000);
```
![screenshot](https://user-images.githubusercontent.com/9327685/28824230-cdf0dbfa-76c9-11e7-97c0-928d98da836e.png)

**Comment by lashket** [comment] 2017-08-01 11:59
No, but if im using this, it works fine:
```
        new Handler().postDelayed(() ->
                new FancyShowCaseView.Builder(MainActivity.this)
                .focusOn(toolbarTabLayout.getTabAt(0).getCustomView())
                .build()
                .show(), 5000);
```
![screenshot](https://user-images.githubusercontent.com/9327685/28824280-04dd8f8c-76ca-11e7-9b95-9c31b3e32dbb.png)

**Comment by faruktoptas** [comment] 2017-08-01 13:31
So is the problem with fitSystemWindows or not?

**Comment by lashket** [comment] 2017-08-01 13:34
No, i can't understand what is the problem. I don't use fitSystemWindows in this activity
It work fine only when i add postDelayd

**Comment by faruktoptas** [comment] 2017-08-01 13:37
I will try to reproduce it. It can be a special case for TabLayout. Can you share your activity layout?

**Comment by lashket** [comment] 2017-08-01 13:41
Yes, of course
[Source](https://gist.github.com/lashket/dc7d40bf628f9d9f0cec798be7dd8741)

**Comment by faruktoptas** [comment] 2017-08-01 13:47
Thanks @lashket I will try to find the problem. PercentageLayout may cause it. I've not tried it before.

**Comment by faruktoptas** [comment] 2019-05-22 22:49
Closed due to inactivity. Can be reopened with steps to reproduce.

**Closed by faruktoptas** 2019-05-22 22:49 UTC
